CREATE DATABASE HEALTH_CLINIC_T;

USE HEALTH_CLINIC_T;

CREATE TABLE TipoUsuario
(
IdTipoUsuario INT PRIMARY KEY IDENTITY,
Tipo Varchar (25) NOT NULL 
);

CREATE TABLE Especialidade
(
IdEspecialidade INT PRIMARY KEY IDENTITY,
Tipo varchar (50) NOT NULL
);

CREATE TABLE Paciente
(
IdPaciente INT PRIMARY KEY IDENTITY,
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
CPF VARCHAR (20) NOT NULL UNIQUE,
RG VARCHAR (25) NOT NULL UNIQUE,
CEP VARCHAR (25)NOT NULL,
Endereco VARCHAR (50) NOT NULL,
Telefone VARCHAR (20) NOT NULL
);

CREATE TABLE Feedback
(
IdFeedback INT PRIMARY KEY IDENTITY,
Descricao VARCHAR (500)
);

ALTER TABLE Feedback
ALTER COLUMN Descricao VARCHAR (500)

CREATE TABLE Clinica
(
IdClinica INT PRIMARY KEY IDENTITY,
Endereco VARCHAR (70) NOT NULL,
HorarioFuncionamento VARCHAR (35),
CNPJ VARCHAR (35) NOT NULL,
NomeFantasia VARCHAR (30) NOT NULL,
RazaoSocial VARCHAR (35) NOT NULL
);

CREATE TABLE Usuario
(
IdUsuario INT PRIMARY KEY IDENTITY,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
Nome VARCHAR (40) NOT NULL,
Senha VARCHAR (20) NOT NULL,
Email VARCHAR (35) NOT NULL UNIQUE,
);

CREATE TABLE Medico
(
IdMedico INT PRIMARY KEY IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade),
IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
CRM VARCHAR (25) NOT NULL UNIQUE
);

CREATE TABLE Consulta
(
IdConsulta INT PRIMARY KEY IDENTITY,
IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente),
IdFeedback INT FOREIGN KEY REFERENCES Feedback(IdFeedback),
IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico),
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
DataConsulta DATE,
HorarioConsulta VARCHAR (10),
Prontuario VARCHAR (1000)
);

ALTER TABLE Consulta
ADD Prontuario VARCHAR (1000)

f


