CREATE DATABASE Exercicio_1_4T

--DDL

USE Exercicio_1_4T;

CREATE TABLE Artistas
(
IdArtista INT PRIMARY KEY IDENTITY,
Nome VARCHAR(25)
);

CREATE TABLE Albuns
(
IdAlbum INT PRIMARY KEY IDENTITY,
IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) NOT NULL,

Titulo VARCHAR(50) NOT NULL,
DataLancamento DATE NOT NULL,
Localizacao VARCHAR(255) NOT NULL,
QtdMin VARCHAR(5) NOT NULL,
Ativo BIT NOT NULL

);

CREATE TABLE GenerosMsc(
IdGenero INT PRIMARY KEY IDENTITY,
Nome VARCHAR(25) NOT NULL
);

CREATE TABLE EstiloMusical
(
IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum) NOT NULL,
IdGenero INT FOREIGN KEY REFERENCES GenerosMsc(IdGenero) NOT NULL
)

CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY,
Nome VARCHAR(20) NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha CHAR(20) NOT NULL,
Permissao BIT NOT NULL
)

drop table Estilos
